- name: new server baseline
#  hosts: 10.11.11.162
#  remote_user: mread 
   
  tasks:
  - name: Run the equivalent of "apt-get update" as a separate step
    ansible.builtin.apt:
      update_cache: yes

  - name: Update all packages to their latest version
    ansible.builtin.apt:
      name: "*"
      state: latest

  - name: Upgrade the OS (apt-get dist-upgrade)
    ansible.builtin.apt:
      upgrade: dist

  - name: Install a list of packages
    ansible.builtin.apt:
      pkg:
      - vim
      - qemu-guest-agent # start service
      - curl
      - wget
      - net-tools

  - name: Make sure a qemu-guest-agent unit is running
    ansible.builtin.systemd_service:
      state: started
      name: qemu-guest-agent